# Generated by Django 6.0.8 on 2026-10-01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("offers", "0006_alter_message_options_and_more"),
        ("offers", "0006_offer_comment_offer_delivery_days_alter_offer_price_and_more"),
    ]

    operations = []
